
loopback_ip: 1.1.1.11

underlay:
    local:
        asn: 60011
    neighbors:
      - interface: em5
        name: spine1
        asn: 60001
        peer_ip: "{{ p2p.link1.1 }}"
        local_ip: "{{ p2p.link1.2 }}"
      - interface: em6
        name: spine2
        asn: 60002
        peer_ip: "{{ p2p.link2.1 }}"
        local_ip: "{{ p2p.link2.2 }}"

junos_std_l3:
    - name: em7
      units:
      - id: 0
        ip: 172.16.1.1
        mask: 24
