---
- name: Gather facts from Junos devices
  hosts: vqfx1
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Gather Junos facts with no configuration
      juniper_junos_facts:
