
inet_interfaces:
    - name: xe-0/0/0
      ip: 10.0.0.2/30
      description: "connect 2 vqfx1"
    - name: lo0
      ip: 9.9.9.2/32
      description: "vxlan source"      

vxlan_interfaces:
    - name: xe-0/0/1
      description: "server21"
      vxlan_id: 10000
      vlan_id: 100
      vlan_name: servers100
      irb_ip: 10.10.1.252/24
      vga_ip: 10.10.1.254
      vga_mac: 00:01:95:00:01:01

    - name: xe-0/0/2
      description: "server22"
      vxlan_id: 20000
      vlan_id: 200
      vlan_name: servers200
      irb_ip: 10.10.2.252/24
      vga_ip: 10.10.2.254
      vga_mac: 00:01:95:00:01:02

router_id: 9.9.9.2
neighbor: 9.9.9.1
route_distinguisher: "9992:1"
vrf_target: "target:64500:9992"
local_address: 9.9.9.2
